server:
  port: 8080
eureka:
  client:
    register-with-eureka: true # register gateway server in eureka server
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka # eureka server ip


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/ # 전송할 ip
          predicates:
            - Path=/users/login  # 로그인
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 쿠키에 대한 정보 삭제
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/signup # 회원가입
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/email-certification # 인증코드 전송
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
#        - id: user-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/users/email-code-check # 인증코드 확인
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/reissue   # access token 재발급
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter

        - id: activity-service
          uri: http://localhost:8082/
          predicates:
            - Path=/activity/**
          filters:
            - AuthorizationHeaderFilter

        - id: newsfeed-service
          uri: http://localhost:8083/
          predicates:
            - Path=/newsfeeds/**
          filters:
            - AuthorizationHeaderFilter

        - id: product-service
          uri: http://localhost:8084/
          predicates:
            - Path=/products/**

        - id: stock-service
          uri: http://localhost:8085/
          predicates:
            - Path=/stocks/**

        - id: payment-service
          uri: http://localhost:8086/
          predicates:
            - Path=/payments/**

        - id: purchase-service
          uri: http://localhost:8087/
          predicates:
            - Path=/purchases/**

  profiles:
    include: config


