server:
  port: 8000
eureka:
  client:
    register-with-eureka: true # register gateway server in eureka server
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka # eureka server ip


spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/ # 전송할 ip
          predicates:
            - Path=/users/login  # 로그인
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 쿠키에 대한 정보 삭제
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/signup # 회원가입
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/email-certification # 인증코드 전송
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/email-code-check # 인증코드 확인
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/reissue   # access token 재발급
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter
  profiles:
    include: config


